version: '3.8'

services:
  mysql-ecommerce:
    image: mysql:8.0
    container_name: mysql-ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data_ecommerce:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-ecommerce:
    image: redis:7
    container_name: redis-ecommerce
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data_ecommerce:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq-ecommerce:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-ecommerce
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_ecommerce:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  dbmate-ecommerce:
    image: amacneil/dbmate:latest
    container_name: dbmate-ecommerce
    depends_on:
      mysql-ecommerce:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for MySQL...' &&
        dbmate --wait --url mysql://root:${DB_PASSWORD}@mysql-ecommerce:3306/${DB_NAME} up
      "
    environment:
      DATABASE_URL: "mysql://root:${DB_PASSWORD}@mysql-ecommerce:3306/${DB_NAME}"
    volumes:
      - ./db/migrations:/db/migrations

  app-ecommerce:
    build: .
    container_name: app-ecommerce
    depends_on:
      mysql-ecommerce:
        condition: service_healthy
      redis-ecommerce:
        condition: service_healthy
      rabbitmq-ecommerce:
        condition: service_healthy
      dbmate-ecommerce:
        condition: service_started
    env_file:
      - .env-local-docker
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: ["/e-commerce"]
    restart: always

volumes:
  db_data_ecommerce:
  redis_data_ecommerce:
  rabbitmq_data_ecommerce:
